server:
  port: 9090
jwt:
  secret: $2a$10$MoBWTFprbCWN9tXBEtgvM.C.vn5ox2MV6qgw9jlRu4jASuaLL5uDa
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/userDB
    username: postgres
    password: root
  jpa:
    database: POSTGRESQL
    show-sql: true
    generate-ddl: true
    hibernate:
      ddl-auto: update


